---
apiVersion: v1
kind: Namespace
metadata:
  name: smiap-k8s
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: smiap-k8s
  namespace: smiap-k8s
  labels:
    app: smiap-k8s
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: smiap-k8s
rules:
  - apiGroups:
    - ""
    resources:
    - services
    - configmaps
    - persistentvolumeclaims
    - pods
    - namespaces
    - persistentvolumes
    verbs:
    - "*"
  - apiGroups:
    - "apps"
    resources:
    - statefulsets
    verbs:
    - "*"
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: smiap-k8s
  namespace: default
subjects:
  - kind: ServiceAccount
    name: smiap-k8s
    namespace: smiap-k8s
roleRef:
  kind: ClusterRole
  name: smiap-k8s
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: smiap-k8s
  namespace: smiap-k8s
  labels:
    app: smiap-k8s
spec:
  replicas: 1
  selector:
    matchLabels:
      app: smiap-k8s
  template:
    metadata:
      labels:
        app: smiap-k8s
    spec:
      serviceAccountName: smiap-k8s
      containers:
      - name: smiap-k8s
        image: localhost:5000/smiap-k8s
        imagePullPolicy: Always
        resources:
          requests:
            memory: "64Mi"
            cpu: "500m"
          limits:
            memory: "128Mi"
            cpu: "1000m"
